"""Command: roco completion"""

import argparse

from robo_cortex.cli._common import cli_command

_TEMPLATE = """# roco / robo-cortex bash completion
# Generated by `roco completion bash`. Install with:
#   roco completion bash >> ~/.bashrc
# or system-wide (Debian/Ubuntu):
#   roco completion bash | sudo tee /etc/bash_completion.d/roco
# Regenerate after upgrading robo-cortex, to pick up new commands or flags.
_roco_completions()
{
    local cur commands
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"

    commands="__COMMANDS__"

    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
        return 0
    fi

    case "${COMP_WORDS[1]}" in
__CASES__
    esac
}
complete -F _roco_completions roco
complete -F _roco_completions robo-cortex
"""


def _bash_completion_script() -> str:
    """Introspect the real argparse tree (same one `main()` dispatches
    through -- see `cli.app.build_parser`) rather than hand-maintaining a
    second, driftable list of commands and flags.

    Only two levels are completed: the subcommand name, and that
    subcommand's own flags -- not nested sub-subcommands (`hooks install`,
    `evidence add`) or flag *values* (paths, statuses). Documented
    limitation, not an oversight: extend only if it proves to matter in
    practice (KISS).
    """
    from robo_cortex.cli.app import build_parser  # deferred: app.py imports
    # cli.commands at module load time, which imports this module -- a
    # top-level import here would be circular.

    parser = build_parser("roco")
    subparsers_action = next(
        action for action in parser._actions
        if isinstance(action, argparse._SubParsersAction)
    )
    command_names = sorted(subparsers_action.choices)

    case_blocks = []
    for name in command_names:
        subparser = subparsers_action.choices[name]
        flags = sorted({
            option
            for action in subparser._actions
            for option in action.option_strings
        })
        flags_str = " ".join(flags)
        case_blocks.append(
            f'        {name})\n'
            f'            COMPREPLY=( $(compgen -W "{flags_str}" -- "$cur") )\n'
            f'            ;;'
        )

    return (
        _TEMPLATE
        .replace("__COMMANDS__", " ".join(command_names))
        .replace("__CASES__", "\n".join(case_blocks))
    )


@cli_command("completion")
def run(args) -> int:
    if args.shell == "bash":
        print(_bash_completion_script(), end="")
    return 0


def register(subparsers):
    p = subparsers.add_parser(
        "completion", help="Generate a shell completion script"
    )
    p.add_argument(
        "shell", choices=["bash"],
        help="Shell to generate a completion script for",
    )
    p.set_defaults(func=run)
